"""fase 5: lsc_sign_templates

Revision ID: 8694e46bd489
Revises: ea1475fd58a0
Create Date: 2026-09-11 19:45:04.284007

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8694e46bd489'
down_revision: Union[str, None] = 'ea1475fd58a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lsc_sign_templates',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('sign_id', sa.Uuid(), nullable=False),
    sa.Column('video_id', sa.Uuid(), nullable=False),
    sa.Column('landmark_sequence', sa.Text(), nullable=False),
    sa.Column('frame_count', sa.Integer(), nullable=False),
    sa.Column('hand_detection_frames', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['sign_id'], ['lsc_signs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['video_id'], ['lsc_videos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lsc_sign_templates')
    # ### end Alembic commands ###
